global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: hobsinn-services
    metrics_path: /actuator/prometheus
    static_configs:
      - targets:
          - hobsinn-api-gateway:8080
          - hobsinn-user-service:8086
          - hobsinn-scheduling-service:8081
          - hobsinn-provider-service:8087
          - hobsinn-payment-service:8084
          - hobsinn-campaign-service:8082
          - hobsinn-reporting-service:8083
          - hobsinn-notification-service:8085
          - hobsinn-analytics-service:8088
